version: 2
jobs:
  build:
    docker:
      - image: golang
    steps:
      - run:
          name: Deployment
          command: |
            git clone -b ${CIRCLE_BRANCH} https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git
            cd ${CIRCLE_PROJECT_REPONAME}

            # aliyun-cli, jq, aliyun cli profileの準備
            tar -xzvf ./library/aliyun-cli-linux-3.0.4-amd64.tgz -C /bin/
            mv ./library/jq /bin/
            aliyun configure set --mode AK --region ${REGION} --access-key-id ${ACCESS_KEY_ID} --access-key-secret ${ACCESS_KEY_SECRET}

            # コマンドの実行
            if [ ${SHELL} == "enable_console_logon.sh" ];then /bin/bash ${SHELL} ${PASSWORD_STRING}; fi
            if [ ${SHELL} == "disable_console_logon.sh" ];then /bin/bash ${SHELL}; fi
            if [ ${SHELL} == "delete_resource_all.sh" ];then /bin/bash ${SHELL} ${REGION} ${ASSUME_ROLE_ARN}; fi
